apiVersion: batch/v1
kind: CronJob
metadata:
  name: normans-row-inserter
  namespace: db-stress
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: row-inserter
            image: frenoid/row-inserter:v4
            env:
            - name: MYSQL_HOST
              value: "tidb-cluster-tidb.tidb.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: ""
            - name: MYSQL_PORT
              value: "4000"
            - name: MYSQL_DATABASE
              value: "test"
            - name: NO_OF_ROWS
              value: "5"
            - name: WRITE_MODE
              value: "CONTINUOUS"
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
